### ISSUE TITLE
jsthemis build error with nodejs 6.3.0

### ISSUE THREAD

**Issue by Lagovas** [cossacklabs/themis#124]
```
[lagovas@localhost js]$ npm install jsthemis

> jsthemis@0.9.3 preinstall /home/lagovas/development/tutorials/js/node_modules/.staging/jsthemis-072db551
> node-gyp configure && node-gyp build

make: Entering directory '/home/lagovas/development/tutorials/js/node_modules/.staging/jsthemis-072db551/build'
  CXX(target) Release/obj.target/jsthemis/addon.o
In file included from ../addon.cpp:18:0:
../secure_message.hpp:25:49: error: expected class-name before ‘{’ token
   class SecureMessage : public node::ObjectWrap {
                                                 ^
../secure_message.hpp:33:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                ^~~~~~~~~
../secure_message.hpp:34:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> encrypt(const v8::Arguments& args);
                                                    ^~~~~~~~~
../secure_message.hpp:35:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> decrypt(const v8::Arguments& args);
                                                    ^~~~~~~~~
../secure_message.hpp:36:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> sign(const v8::Arguments& args);
                                                 ^~~~~~~~~
../secure_message.hpp:37:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> verify(const v8::Arguments& args);
                                                   ^~~~~~~~~
In file included from ../addon.cpp:19:0:
../secure_keygen.hpp:25:43: error: expected class-name before ‘{’ token
   class KeyPair : public node::ObjectWrap {
                                           ^
../secure_keygen.hpp:34:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                ^~~~~~~~~
../secure_keygen.hpp:35:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> private_key(const v8::Arguments& args);
                                                        ^~~~~~~~~
../secure_keygen.hpp:36:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> public_key(const v8::Arguments& args);
                                                       ^~~~~~~~~
In file included from ../addon.cpp:20:0:
../secure_session.hpp:26:49: error: expected class-name before ‘{’ token
   class SecureSession : public node::ObjectWrap {
                                                 ^
In file included from ../addon.cpp:20:0:
../secure_session.hpp:34:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                ^~~~~~~~~
../secure_session.hpp:35:59: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> connectRequest(const v8::Arguments& args);
                                                           ^~~~~~~~~
../secure_session.hpp:36:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> wrap(const v8::Arguments& args);
                                                 ^~~~~~~~~
../secure_session.hpp:37:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> unwrap(const v8::Arguments& args);
                                                   ^~~~~~~~~
../secure_session.hpp:38:58: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> isEstablished(const v8::Arguments& args);
                                                          ^~~~~~~~~
In file included from ../addon.cpp:21:0:
../secure_cell_seal.hpp:25:50: error: expected class-name before ‘{’ token
   class SecureCellSeal : public node::ObjectWrap {
                                                  ^
../secure_cell_seal.hpp:33:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                ^~~~~~~~~
../secure_cell_seal.hpp:34:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> encrypt(const v8::Arguments& args);
                                                    ^~~~~~~~~
../secure_cell_seal.hpp:35:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> decrypt(const v8::Arguments& args);
                                                    ^~~~~~~~~
In file included from ../addon.cpp:22:0:
../secure_cell_context_imprint.hpp:25:60: error: expected class-name before ‘{’ token
   class SecureCellContextImprint : public node::ObjectWrap {
                                                            ^
../secure_cell_context_imprint.hpp:33:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                ^~~~~~~~~
../secure_cell_context_imprint.hpp:34:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> encrypt(const v8::Arguments& args);
                                                    ^~~~~~~~~
../secure_cell_context_imprint.hpp:35:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> decrypt(const v8::Arguments& args);
                                                    ^~~~~~~~~
In file included from ../addon.cpp:23:0:
../secure_cell_token_protect.hpp:25:58: error: expected class-name before ‘{’ token
   class SecureCellTokenProtect : public node::ObjectWrap {
                                                          ^
../secure_cell_token_protect.hpp:33:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                ^~~~~~~~~
../secure_cell_token_protect.hpp:34:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> encrypt(const v8::Arguments& args);
                                                    ^~~~~~~~~
../secure_cell_token_protect.hpp:35:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     static v8::Handle<v8::Value> decrypt(const v8::Arguments& args);
                                                    ^~~~~~~~~
make: *** [jsthemis.target.mk:98: Release/obj.target/jsthemis/addon.o] Error 1
make: Leaving directory '/home/lagovas/development/tutorials/js/node_modules/.staging/jsthemis-072db551/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.6.4-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/lagovas/development/tutorials/js/node_modules/.staging/jsthemis-072db551
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.6.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "jsthemis"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! jsthemis@0.9.3 preinstall: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsthemis@0.9.3 preinstall script 'node-gyp configure && node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jsthemis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsthemis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jsthemis
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lagovas/development/tutorials/js/npm-debug.log
[lagovas@localhost js]$ node -v
v6.3.0
```

**Comment by mnaza** [comment]
Closed by #137
