### ISSUE TITLE
Error installing jsthemis by NPM - ../secure_session.hpp:22:10: fatal error: 'themis/themis.h' file not found

### ISSUE THREAD

**Issue by genemyers** [cossacklabs/themis#318]
This looks similar to issue #237 except I am trying to install by the latest npm 0.10.0 and not building the source.

----------------------------------------

### Issue description
this is the error I get:
```
 $npm update

> jsthemis@0.9.6 install /Users/gene/SRC/jsthemis_test/node_modules/jsthemis
> node-gyp rebuild

2018-08-21 10:48:21.475 xcodebuild[4275:24900] [MT] PluginLoading: Required plug-in compatibility UUID 426A087B-D3AA-431A-AFDF-F135EC00DE1C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/jsthemis/addon.o
In file included from ../addon.cpp:20:
../secure_session.hpp:22:10: fatal error: 'themis/themis.h' file not found
#include <themis/themis.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/jsthemis/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/gene/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/gene/.nvm/versions/node/v8.11.4/bin/node" "/Users/gene/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gene/SRC-WYLD/dh_node_test/node_modules/jsthemis
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsthemis@0.9.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsthemis@0.9.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Environment info

**OS:**  macOS High Sierra 10.13.6
Node- v8.11.4

**Themis NPM version:** 0.10.0

openssl version: LibreSSL 2.2.7

**Crypto provider:** OpenSSL / BoringSSL / LibreSSL (v0.0.0)

I understand from issue #237 that the script cannot find OpenSSL

$brew --prefix openssl    
returns:
/usr/local/opt/openssl

$ which openssl  
returns:
/usr/bin/openssl

macOS High Sierra seems to have changed openssl implementations to LibreSSL, which I'm wondering if is the cause of my issue?

**Comment by genemyers** [comment]
I have also tested in an Ubuntu Server 16.04 LTS and got the same result.
Here the OpenSLL version returns:OpenSSL 1.0.2g  1 Mar 2016

**Comment by vixentael** [comment]
Hi @genemyers! 

It looks more like a problem with installing Themis for Node v10.

In Node v10 they updated gyp a lot:

```
A direct solution for this issue might be to modernize the node-gyp layer to be compatible with Node.js 10.x which has evolved NewInstance since this library was last published.
```
(from https://github.com/phusion/node-sha3/issues/32)

We use [gyp layer](https://github.com/cossacklabs/themis/tree/master/src/wrappers/themis/jsthemis) to compile Themis C sources and made them available from js side, so we need to update gyp building for compatibility with Node v10.

I suggest you following:

1. Downgrade Node version to the previous one (before v10).
2. Install latest Themis:

```
npm install jsthemis@0.10.0
```

3. Let us know if it helped.

-------------

On my machine:

```
$ node -v                    
v8.11.3
$ npm -v
5.6.0
$ npm install jsthemis@0.10.0
> jsthemis@0.10.0 install /Users/dff/node_modules/jsthemis
> node-gyp rebuild

....

+ jsthemis@0.10.0
added 1 package in 14.708s
```

We would appreciate if you are familiar with gyp and can help with updating gyp installation instructions. Any way, this update is on our list.

**Comment by genemyers** [comment]
Thanks vixentael!

On MacOS you'll note that I am using Node 8.11.4, but there may be issues related to LibraSSL there too?

 I will downgrade Node on Ubuntu and give it a try and let you know.

**Comment by genemyers** [comment]
hello vixentael, I've downgraded Node to 8.11.3 
```
ubuntu@ip-172-31-14-144:~$ node --version
v8.11.3
ubuntu@ip-172-31-14-144:~$ npm -v
5.6.0
```

I'm still getting a similar error:
```
ubuntu@ip-172-31-14-144:~$ npm install jsthemis@0.10.0

> jsthemis@0.10.0 install /home/ubuntu/node_modules/jsthemis
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/ubuntu/node_modules/jsthemis/build'
  CXX(target) Release/obj.target/jsthemis/addon.o
In file included from ../addon.cpp:20:0:
../secure_session.hpp:22:27: fatal error: themis/themis.h: No such file or directory
compilation terminated.
jsthemis.target.mk:102: recipe for target 'Release/obj.target/jsthemis/addon.o' failed
make: *** [Release/obj.target/jsthemis/addon.o] Error 1
make: Leaving directory '/home/ubuntu/node_modules/jsthemis/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-1061-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v8.11.3/bin/node" "/home/ubuntu/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/node_modules/jsthemis
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm WARN ubuntu No description
npm WARN ubuntu No repository field.
npm WARN ubuntu No README data
npm WARN ubuntu No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsthemis@0.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsthemis@0.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/ubuntu/.config │
└──────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-21T10_49_46_902Z-debug.log
```

I did try then runnning as sudo and got a different error:
```
ubuntu@ip-172-31-14-144:~$ sudo npm install jsthemis@0.10.0

> jsthemis@0.10.0 install /home/ubuntu/node_modules/jsthemis
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ubuntu/node_modules/jsthemis/build'
gyp ERR! System Linux 4.4.0-1061-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/node_modules/jsthemis
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm WARN ubuntu No description
npm WARN ubuntu No repository field.
npm WARN ubuntu No README data
npm WARN ubuntu No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsthemis@0.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsthemis@0.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-21T10_54_10_296Z-debug.log
```

**Comment by vixentael** [comment]
If you have any suggestions how to update Installation guide for NodeJS to make it clear, that Themis main library should be installed first, please let us know. 

We want to improve docs to be super-clear on that 😬

**Comment by genemyers** [comment]
OK *vixentael*
It's installed now, thank you, and yes, the documentation could use improvement. I do have a few suggestions for updating the jsthemis guide- I'm going to document the steps for our team. I'd be happy to send them to you.

**Comment by vixentael** [comment]
Great! 🙌

Thank you @genemyers!

We would really appreciate that. Please send steps to [dev@cossacklabs.com](mailto:dev@cossacklabs.com) or post right here.
